FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json yarn.lock .yarnrc.yml ./
COPY .yarn/ ./.yarn/
COPY apps/web/package*.json ./apps/web/
RUN corepack enable && yarn install
COPY . .
RUN yarn build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
